
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/anstrofon/\u0417\u0430\u0432\u0430\u043d\u0442\u0430\u0436\u0435\u043d\u0435/CLion/clion-2023.3.4/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.12.4-arch1-1 - x86_64
...
